<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Faker\Factory as Faker;

class EDRSeeder extends Seeder
{

    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $faker = Faker::create();

        DB::table('edrs')->insert([
            'edr_id' => 2,
            'polarity' => 'pos',
            'run_hours' => 800,
            'feed_cl2' => $faker->randomFloat(2, .02, .60),
            'feed_ph' => $faker->randomFloat(2, 6.4, 7.4),
            'feed_temp' => $faker->randomFloat(2, 60.0, 83.0),
            'feed_cond' => $faker->numberBetween(1700, 2400),
            'product_cond' => $faker->numberBetween(440, 520),
            'concen_cond' => $faker->numberBetween(9000, 11800),
            'electrode_inlet_ph' => $faker->randomFloat(2, 5.4, 6.4),
            'post_cart_psi' => $faker->randomFloat(2, 50.0, 68.0),
            'stack_inlet_psi' => $faker->randomFloat(2, 15.0, 30.0),
            'inlet_press_dif' => $faker->randomFloat(2, 1.0, 5.0),
            'outlet_press_dif' => $faker->randomFloat(2, 1.0, 6.0),
            'dil_stack_outlet_psi' => $faker->randomFloat(2, 6.0, 30.0),
            'conc_stack_inlet_psi' => $faker->randomFloat(2, 5.0, 22.0),
            'feed_inlet_flow' => $faker->numberBetween(1000, 2238),
            'dil_outlet_flow' =>  $faker->numberBetween(400, 578),
            'cbd_flow' =>  $faker->numberBetween(400, 578),
            'conc_pump_kw' =>  $faker->randomFloat(2, 15.0, 35.0),
            'conc_pump_speed' => $faker->randomFloat(2, 70.0, 100.0),
            'feed_valve_pos' =>  $faker->randomFloat(2, 30.0, 100.0),
            'electrode_dosage' =>  $faker->randomFloat(2, 0.04, 1.50),
            'antiscalant_dosage' =>  $faker->randomFloat(2, 0.04, 1.50),
            'osp_time' =>  $faker->numberBetween(20, 80),
            'date' =>  \Carbon\Carbon::now()->startOfMonth()->addDays(1)->format('Y-m-d H:i:s'),
            'created_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
        ]);

        DB::table('edrs')->insert([
            'edr_id' => 2,
            'polarity' => 'neg',
            'run_hours' => 801,
            'feed_cl2' => $faker->randomFloat(2, .02, .60),
            'feed_ph' => $faker->randomFloat(2, 6.4, 7.4),
            'feed_temp' => $faker->randomFloat(2, 60.0, 83.0),
            'feed_cond' => $faker->numberBetween(1700, 2400),
            'product_cond' => $faker->numberBetween(440, 520),
            'concen_cond' => $faker->numberBetween(9000, 11800),
            'electrode_inlet_ph' => $faker->randomFloat(2, 5.4, 6.4),
            'post_cart_psi' => $faker->randomFloat(2, 50.0, 68.0),
            'stack_inlet_psi' => $faker->randomFloat(2, 15.0, 30.0),
            'inlet_press_dif' => $faker->randomFloat(2, 1.0, 5.0),
            'outlet_press_dif' => $faker->randomFloat(2, 1.0, 6.0),
            'dil_stack_outlet_psi' => $faker->randomFloat(2, 6.0, 30.0),
            'conc_stack_inlet_psi' => $faker->randomFloat(2, 5.0, 22.0),
            'feed_inlet_flow' => $faker->numberBetween(1000, 2238),
            'dil_outlet_flow' =>  $faker->numberBetween(400, 578),
            'cbd_flow' =>  $faker->numberBetween(400, 578),
            'conc_pump_kw' =>  $faker->randomFloat(2, 15.0, 35.0),
            'conc_pump_speed' => $faker->randomFloat(2, 70.0, 100.0),
            'feed_valve_pos' =>  $faker->randomFloat(2, 30.0, 100.0),
            'electrode_dosage' =>  $faker->randomFloat(2, 0.04, 1.50),
            'antiscalant_dosage' =>  $faker->randomFloat(2, 0.04, 1.50),
            'osp_time' =>  $faker->numberBetween(20, 80),
            'date' =>  \Carbon\Carbon::now()->startOfMonth()->addDays(1)->format('Y-m-d H:i:s'),
            'created_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
        ]);

        DB::table('edrs')->insert([
            'edr_id' => 2,
            'polarity' => 'pos',
            'run_hours' => 800,
            'feed_cl2' => $faker->randomFloat(2, .02, .60),
            'feed_ph' => $faker->randomFloat(2, 6.4, 7.4),
            'feed_temp' => $faker->randomFloat(2, 60.0, 83.0),
            'feed_cond' => $faker->numberBetween(1700, 2400),
            'product_cond' => $faker->numberBetween(440, 520),
            'concen_cond' => $faker->numberBetween(9000, 11800),
            'electrode_inlet_ph' => $faker->randomFloat(2, 5.4, 6.4),
            'post_cart_psi' => $faker->randomFloat(2, 50.0, 68.0),
            'stack_inlet_psi' => $faker->randomFloat(2, 15.0, 30.0),
            'inlet_press_dif' => $faker->randomFloat(2, 1.0, 5.0),
            'outlet_press_dif' => $faker->randomFloat(2, 1.0, 6.0),
            'dil_stack_outlet_psi' => $faker->randomFloat(2, 6.0, 30.0),
            'conc_stack_inlet_psi' => $faker->randomFloat(2, 5.0, 22.0),
            'feed_inlet_flow' => $faker->numberBetween(1000, 2238),
            'dil_outlet_flow' =>  $faker->numberBetween(400, 578),
            'cbd_flow' =>  $faker->numberBetween(400, 578),
            'conc_pump_kw' =>  $faker->randomFloat(2, 15.0, 35.0),
            'conc_pump_speed' => $faker->randomFloat(2, 70.0, 100.0),
            'feed_valve_pos' =>  $faker->randomFloat(2, 30.0, 100.0),
            'electrode_dosage' =>  $faker->randomFloat(2, 0.04, 1.50),
            'antiscalant_dosage' =>  $faker->randomFloat(2, 0.04, 1.50),
            'osp_time' =>  $faker->numberBetween(20, 80),
            'date' =>  \Carbon\Carbon::now()->startOfMonth()->addDays(2)->format('Y-m-d H:i:s'),
            'created_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
        ]);

        DB::table('edrs')->insert([
            'edr_id' => 2,
            'polarity' => 'neg',
            'run_hours' => 800,
            'feed_cl2' => $faker->randomFloat(2, .02, .60),
            'feed_ph' => $faker->randomFloat(2, 6.4, 7.4),
            'feed_temp' => $faker->randomFloat(2, 60.0, 83.0),
            'feed_cond' => $faker->numberBetween(1700, 2400),
            'product_cond' => $faker->numberBetween(440, 520),
            'concen_cond' => $faker->numberBetween(9000, 11800),
            'electrode_inlet_ph' => $faker->randomFloat(2, 5.4, 6.4),
            'post_cart_psi' => $faker->randomFloat(2, 50.0, 68.0),
            'stack_inlet_psi' => $faker->randomFloat(2, 15.0, 30.0),
            'inlet_press_dif' => $faker->randomFloat(2, 1.0, 5.0),
            'outlet_press_dif' => $faker->randomFloat(2, 1.0, 6.0),
            'dil_stack_outlet_psi' => $faker->randomFloat(2, 6.0, 30.0),
            'conc_stack_inlet_psi' => $faker->randomFloat(2, 5.0, 22.0),
            'feed_inlet_flow' => $faker->numberBetween(1000, 2238),
            'dil_outlet_flow' =>  $faker->numberBetween(400, 578),
            'cbd_flow' =>  $faker->numberBetween(400, 578),
            'conc_pump_kw' =>  $faker->randomFloat(2, 15.0, 35.0),
            'conc_pump_speed' => $faker->randomFloat(2, 70.0, 100.0),
            'feed_valve_pos' =>  $faker->randomFloat(2, 30.0, 100.0),
            'electrode_dosage' =>  $faker->randomFloat(2, 0.04, 1.50),
            'antiscalant_dosage' =>  $faker->randomFloat(2, 0.04, 1.50),
            'osp_time' =>  $faker->numberBetween(20, 80),
            'date' =>  \Carbon\Carbon::now()->subMonths(3)->addDays(2)->format('Y-m-d H:i:s'),
            'created_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
        ]);


        DB::table('edrs')->insert([
            'edr_id' => 2,
            'polarity' => 'neg',
            'run_hours' => 800,
            'feed_cl2' => $faker->randomFloat(2, .02, .60),
            'feed_ph' => $faker->randomFloat(2, 6.4, 7.4),
            'feed_temp' => $faker->randomFloat(2, 60.0, 83.0),
            'feed_cond' => $faker->numberBetween(1700, 2400),
            'product_cond' => $faker->numberBetween(440, 520),
            'concen_cond' => $faker->numberBetween(9000, 11800),
            'electrode_inlet_ph' => $faker->randomFloat(2, 5.4, 6.4),
            'post_cart_psi' => $faker->randomFloat(2, 50.0, 68.0),
            'stack_inlet_psi' => $faker->randomFloat(2, 15.0, 30.0),
            'inlet_press_dif' => $faker->randomFloat(2, 1.0, 5.0),
            'outlet_press_dif' => $faker->randomFloat(2, 1.0, 6.0),
            'dil_stack_outlet_psi' => $faker->randomFloat(2, 6.0, 30.0),
            'conc_stack_inlet_psi' => $faker->randomFloat(2, 5.0, 22.0),
            'feed_inlet_flow' => $faker->numberBetween(1000, 2238),
            'dil_outlet_flow' =>  $faker->numberBetween(400, 578),
            'cbd_flow' =>  $faker->numberBetween(400, 578),
            'conc_pump_kw' =>  $faker->randomFloat(2, 15.0, 35.0),
            'conc_pump_speed' => $faker->randomFloat(2, 70.0, 100.0),
            'feed_valve_pos' =>  $faker->randomFloat(2, 30.0, 100.0),
            'electrode_dosage' =>  $faker->randomFloat(2, 0.04, 1.50),
            'antiscalant_dosage' =>  $faker->randomFloat(2, 0.04, 1.50),
            'osp_time' =>  $faker->numberBetween(20, 80),
            'date' =>  \Carbon\Carbon::now()->subMonths(3)->addDays(17)->format('Y-m-d H:i:s'),
            'created_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
        ]);

        DB::table('edrs')->insert([
            'edr_id' => 2,
            'polarity' => 'pos',
            'run_hours' => 800,
            'feed_cl2' => $faker->randomFloat(2, .02, .60),
            'feed_ph' => $faker->randomFloat(2, 6.4, 7.4),
            'feed_temp' => $faker->randomFloat(2, 60.0, 83.0),
            'feed_cond' => $faker->numberBetween(1700, 2400),
            'product_cond' => $faker->numberBetween(440, 520),
            'concen_cond' => $faker->numberBetween(9000, 11800),
            'electrode_inlet_ph' => $faker->randomFloat(2, 5.4, 6.4),
            'post_cart_psi' => $faker->randomFloat(2, 50.0, 68.0),
            'stack_inlet_psi' => $faker->randomFloat(2, 15.0, 30.0),
            'inlet_press_dif' => $faker->randomFloat(2, 1.0, 5.0),
            'outlet_press_dif' => $faker->randomFloat(2, 1.0, 6.0),
            'dil_stack_outlet_psi' => $faker->randomFloat(2, 6.0, 30.0),
            'conc_stack_inlet_psi' => $faker->randomFloat(2, 5.0, 22.0),
            'feed_inlet_flow' => $faker->numberBetween(1000, 2238),
            'dil_outlet_flow' =>  $faker->numberBetween(400, 578),
            'cbd_flow' =>  $faker->numberBetween(400, 578),
            'conc_pump_kw' =>  $faker->randomFloat(2, 15.0, 35.0),
            'conc_pump_speed' => $faker->randomFloat(2, 70.0, 100.0),
            'feed_valve_pos' =>  $faker->randomFloat(2, 30.0, 100.0),
            'electrode_dosage' =>  $faker->randomFloat(2, 0.04, 1.50),
            'antiscalant_dosage' =>  $faker->randomFloat(2, 0.04, 1.50),
            'osp_time' =>  $faker->numberBetween(20, 80),
            'date' =>  \Carbon\Carbon::now()->subMonths(5)->addDays(1)->format('Y-m-d H:i:s'),
            'created_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
        ]);

        DB::table('edrs')->insert([
            'edr_id' => 2,
            'polarity' => 'pos',
            'run_hours' => 800,
            'feed_cl2' => $faker->randomFloat(2, .02, .60),
            'feed_ph' => $faker->randomFloat(2, 6.4, 7.4),
            'feed_temp' => $faker->randomFloat(2, 60.0, 83.0),
            'feed_cond' => $faker->numberBetween(1700, 2400),
            'product_cond' => $faker->numberBetween(440, 520),
            'concen_cond' => $faker->numberBetween(9000, 11800),
            'electrode_inlet_ph' => $faker->randomFloat(2, 5.4, 6.4),
            'post_cart_psi' => $faker->randomFloat(2, 50.0, 68.0),
            'stack_inlet_psi' => $faker->randomFloat(2, 15.0, 30.0),
            'inlet_press_dif' => $faker->randomFloat(2, 1.0, 5.0),
            'outlet_press_dif' => $faker->randomFloat(2, 1.0, 6.0),
            'dil_stack_outlet_psi' => $faker->randomFloat(2, 6.0, 30.0),
            'conc_stack_inlet_psi' => $faker->randomFloat(2, 5.0, 22.0),
            'feed_inlet_flow' => $faker->numberBetween(1000, 2238),
            'dil_outlet_flow' =>  $faker->numberBetween(400, 578),
            'cbd_flow' =>  $faker->numberBetween(400, 578),
            'conc_pump_kw' =>  $faker->randomFloat(2, 15.0, 35.0),
            'conc_pump_speed' => $faker->randomFloat(2, 70.0, 100.0),
            'feed_valve_pos' =>  $faker->randomFloat(2, 30.0, 100.0),
            'electrode_dosage' =>  $faker->randomFloat(2, 0.04, 1.50),
            'antiscalant_dosage' =>  $faker->randomFloat(2, 0.04, 1.50),
            'osp_time' =>  $faker->numberBetween(20, 80),
            'date' =>  \Carbon\Carbon::now()->subMonths(1)->addDays(12)->format('Y-m-d H:i:s'),
            'created_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
        ]);

        DB::table('edrs')->insert([
            'edr_id' => 2,
            'polarity' => 'neg',
            'run_hours' => 800,
            'feed_cl2' => $faker->randomFloat(2, .02, .60),
            'feed_ph' => $faker->randomFloat(2, 6.4, 7.4),
            'feed_temp' => $faker->randomFloat(2, 60.0, 83.0),
            'feed_cond' => $faker->numberBetween(1700, 2400),
            'product_cond' => $faker->numberBetween(440, 520),
            'concen_cond' => $faker->numberBetween(9000, 11800),
            'electrode_inlet_ph' => $faker->randomFloat(2, 5.4, 6.4),
            'post_cart_psi' => $faker->randomFloat(2, 50.0, 68.0),
            'stack_inlet_psi' => $faker->randomFloat(2, 15.0, 30.0),
            'inlet_press_dif' => $faker->randomFloat(2, 1.0, 5.0),
            'outlet_press_dif' => $faker->randomFloat(2, 1.0, 6.0),
            'dil_stack_outlet_psi' => $faker->randomFloat(2, 6.0, 30.0),
            'conc_stack_inlet_psi' => $faker->randomFloat(2, 5.0, 22.0),
            'feed_inlet_flow' => $faker->numberBetween(1000, 2238),
            'dil_outlet_flow' =>  $faker->numberBetween(400, 578),
            'cbd_flow' =>  $faker->numberBetween(400, 578),
            'conc_pump_kw' =>  $faker->randomFloat(2, 15.0, 35.0),
            'conc_pump_speed' => $faker->randomFloat(2, 70.0, 100.0),
            'feed_valve_pos' =>  $faker->randomFloat(2, 30.0, 100.0),
            'electrode_dosage' =>  $faker->randomFloat(2, 0.04, 1.50),
            'antiscalant_dosage' =>  $faker->randomFloat(2, 0.04, 1.50),
            'osp_time' =>  $faker->numberBetween(20, 80),
            'date' =>  \Carbon\Carbon::now()->startOfMonth()->addDays(2)->format('Y-m-d H:i:s'),
            'created_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
        ]);



        DB::table('edrs')->insert([
            'edr_id' => 4,
            'polarity' => 'pos',
            'run_hours' => 45,
            'feed_cl2' => $faker->randomFloat(2, .02, .60),
            'feed_ph' => $faker->randomFloat(2, 6.4, 7.4),
            'feed_temp' => $faker->randomFloat(2, 60.0, 83.0),
            'feed_cond' => $faker->numberBetween(1700, 2400),
            'product_cond' => $faker->numberBetween(440, 520),
            'concen_cond' => $faker->numberBetween(9000, 11800),
            'electrode_inlet_ph' => $faker->randomFloat(2, 5.4, 6.4),
            'post_cart_psi' => $faker->randomFloat(2, 50.0, 68.0),
            'stack_inlet_psi' => $faker->randomFloat(2, 15.0, 30.0),
            'inlet_press_dif' => $faker->randomFloat(2, 1.0, 5.0),
            'outlet_press_dif' => $faker->randomFloat(2, 1.0, 6.0),
            'dil_stack_outlet_psi' => $faker->randomFloat(2, 6.0, 30.0),
            'conc_stack_inlet_psi' => $faker->randomFloat(2, 5.0, 22.0),
            'feed_inlet_flow' => $faker->numberBetween(1000, 2238),
            'dil_outlet_flow' =>  $faker->numberBetween(400, 578),
            'cbd_flow' =>  $faker->numberBetween(400, 578),
            'conc_pump_kw' =>  $faker->randomFloat(2, 15.0, 35.0),
            'conc_pump_speed' => $faker->randomFloat(2, 70.0, 100.0),
            'feed_valve_pos' =>  $faker->randomFloat(2, 30.0, 100.0),
            'electrode_dosage' =>  $faker->randomFloat(2, 0.04, 1.50),
            'antiscalant_dosage' =>  $faker->randomFloat(2, 0.04, 1.50),
            'osp_time' =>  $faker->numberBetween(20, 80),
            'date' =>  \Carbon\Carbon::now()->startOfMonth()->addDays(1)->format('Y-m-d H:i:s'),
            'created_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
        ]);

    }
}